### PR TITLE
Redmine 3.0.0 compatibility

### PR DESCRIPTION
**Pull request by redcloak**
Removed deprecated syntax for finds, added methods to routes and added small fix to model to allow creation of new TimeLogger instances (time_loggers_controller.rb:18 was throwing an error).
Plugin is compatible with Redmine 2.6.2, though I didn't check if it is with older versions.

### CODE REVIEW

**Comment by bra-fsn** [comment]
One upvote for this :)
Thanks.

**Comment by extra-0** [comment]
+1

**Comment by RazZziel** [comment]
+1!

**Comment by Turboconnard** [comment]
+1

**Comment by speedy32129** [comment]
Please check latest version.

**Pull request closed without merging**
